apiVersion: apps/v1
kind: Deployment

metadata:
  name: myfrontend-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: myfrontend

  template:
    metadata:
      labels:
        app: myfrontend

    spec:
      containers:
        - name: myfrontend-container
          image: myfrontend:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 80